name: Typo
description: Report a Typo
assignees: 
  - PeteyLumpkins
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a typo!
  - type: textarea
    id: where
    attributes:
      label: Description
      description: Please give us a brief description of the typo and where you found it.
      placeholder: 
      value: 
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Anything Else?
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Links? Screenshots? 
      value: 
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    
   
